### ISSUE TITLE
PaginateForUSSD breaks when paginated items have the same identity

### ISSUE THREAD

**Issue by kwakubiney** [hubtel/programmable-services-sdk-dotnet#11]
### Problem Description

This project exposes an API with the following signature:  

```csharp
Task<ProgrammableServiceResponse> PaginateForUssd(Dictionary<string, string> collection, PaginationOptions paginationOptions)
```

In this API, users provide a collection where the dictionary's key represents the display text.  

However, in scenarios where the user wants to display items with a similar structure (e.g., a list of transactions formatted as `"{username} {amount}"`), there is a potential issue. If a user has made identical transactions multiple times, the resulting dictionary would contain duplicate keys. This leads to a `System.ArgumentException: An item with the same key has already been added` error.  

### Proposal  

To address this limitation, I propose introducing an additional API that allows handling duplicate display texts. This new API could use a data structure better suited for this scenario, such as a list of key-value pairs. Here's an example signature:  

```csharp
public async Task<ProgrammableServiceResponse> PaginateForUssdWithDuplicateItems(
    List<(string Key, string Value)> collection,
    PaginationOptions paginationOptions)
```

This approach would enable users to include duplicate display texts while preserving the existing functionality for scenarios where uniqueness is required.  

Not sure how active this repo is but cc @austinejei , you might be interested. Any feedback is welcome.

**Comment by austinejei** [comment]
Hello Kweku,

Good catch.

Augustine Gyawu Adjei
Software Engineer
+233 24944 14 09
